jwt:
  secret : '[a-zA-Z0-9._]^+$Guidelines89797987AlphabeticalArraNumeralsandotherSymbol$'

server:
  port: 8081

### DATABASE ###
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Timesheet
    password:
    username: root
  ### JPA / HIBERNATE ###
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  #  web:
  #    resources:
  #      add-mappings: false